import { fluidClamp } from './fluid';
import type { Tokens } from './load';

export const CSS_VAR_PREFIX = 'bb' as const;

const CATEGORY_SLUG: Record<Exclude<keyof Tokens, 'breakpoint'>, string> = {
  color: 'color',
  space: 'space',
  fontSize: 'font-size',
  fontFamily: 'font-family',
  fontWeight: 'font-weight',
  lineHeight: 'line-height',
  radius: 'radius',
  shadow: 'shadow',
  container: 'container',
};

export type VariableCategory = keyof typeof CATEGORY_SLUG;

/** `--bb-space-4` for (space, 4). */
export function cssVarName(category: VariableCategory, name: string): string {
  return `--${CSS_VAR_PREFIX}-${CATEGORY_SLUG[category]}-${name}`;
}

/** `var(--bb-space-4)` for (space, 4). */
export function cssVar(category: VariableCategory, name: string): string {
  return `var(${cssVarName(category, name)})`;
}

/** Quotes family names that contain spaces. */
export function fontStack(families: string[]): string {
  return families.map((family) => (/\s/.test(family) ? `"${family}"` : family)).join(', ');
}

function value(category: VariableCategory, tokens: Tokens, name: string): string {
  switch (category) {
    case 'fontSize':
      return fluidClamp(tokens.fontSize[name]!);
    case 'fontFamily':
      return fontStack(tokens.fontFamily[name]!);
    default:
      return String(tokens[category][name]);
  }
}

/** `:root { --bb-*: … }` for every token except breakpoints. */
export function generateCssVariables(tokens: Tokens): string {
  const lines: string[] = [];
  for (const category of Object.keys(CATEGORY_SLUG) as VariableCategory[]) {
    for (const name of Object.keys(tokens[category])) {
      lines.push(`  ${cssVarName(category, name)}: ${value(category, tokens, name)};`);
    }
  }
  return `/* Generated by \`pnpm generate\` from tokens.json. Do not edit. */\n:root {\n${lines.join('\n')}\n}\n`;
}
