import type { Tokens } from './load';
import { TOKEN_CATEGORIES } from './load';

function constName(category: string): string {
  return `${category.replace(/([A-Z])/g, '_$1').toUpperCase()}_NAMES`;
}

function typeName(category: string): string {
  return category.charAt(0).toUpperCase() + category.slice(1);
}

/**
 * TypeScript source for `src/generated/names.ts`: const name lists plus
 * `XName` and `XToken` (`"space.4"`) union types per category.
 */
export function generateNamesModule(tokens: Tokens): string {
  const blocks = TOKEN_CATEGORIES.map((category) => {
    const names = Object.keys(tokens[category]).map((name) => `'${name}'`);
    const list = constName(category);
    const type = typeName(category);
    return [
      `export const ${list} = [${names.join(', ')}] as const;`,
      `export type ${type}Name = (typeof ${list})[number];`,
      `export type ${type}Token = \`${category}.\${${type}Name}\`;`,
    ].join('\n');
  });

  const lists = TOKEN_CATEGORIES.map((category) => `  ${category}: ${constName(category)},`);
  blocks.push(
    `/** Name lists keyed by category. */\nexport const CATEGORY_NAME_LISTS = {\n${lists.join('\n')}\n} as const;`,
  );

  return `// Generated by \`pnpm generate\` from tokens.json. Do not edit.\n\n${blocks.join('\n\n')}\n`;
}
