/** Serializes JSON-compatible data as a PHP literal (for opcache-friendly `return [...]` files). */
export function toPhp(value: unknown, indent = ''): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error('Cannot export non-finite number to PHP');
    return String(value);
  }
  if (typeof value === 'string') {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  }

  const next = `${indent}\t`;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    // Short scalar lists stay on one line.
    if (value.every((item) => typeof item !== 'object' || item === null)) {
      return `[${value.map((item) => toPhp(item)).join(', ')}]`;
    }
    return `[\n${value.map((item) => `${next}${toPhp(item, next)},`).join('\n')}\n${indent}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return '[]';
    return `[\n${entries
      .map(([key, item]) => `${next}${toPhp(key)} => ${toPhp(item, next)},`)
      .join('\n')}\n${indent}]`;
  }
  throw new Error(`Cannot export ${typeof value} to PHP`);
}

/** A complete PHP file returning the value. */
export function phpReturnFile(value: unknown, description: string): string {
  return `<?php\n/**\n * ${description}\n * Generated by \`pnpm generate\` from tokens.json. Do not edit.\n *\n * @package Bestenberg\n */\n\nreturn ${toPhp(value)};\n`;
}
