<?php
/**
 * Full-screen editor admin page.
 *
 * @package Bestenberg
 */

declare( strict_types=1 );

namespace Bestenberg\Admin;

/**
 * Registers the "Bestenberg" admin page and mounts the React editor app.
 */
final class EditorPage {

	public const SLUG       = 'bestenberg';
	public const CAPABILITY = 'edit_theme_options';
	public const ROOT_ID    = 'bestenberg-root';
	public const HANDLE     = 'bestenberg-editor';

	/**
	 * Hook suffix returned by add_menu_page().
	 *
	 * @var string
	 */
	private string $hook_suffix = '';

	/**
	 * Registers hooks.
	 */
	public function register(): void {
		add_action( 'admin_menu', array( $this, 'add_menu_page' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
		add_filter( 'admin_body_class', array( $this, 'body_class' ) );
	}

	/**
	 * Adds the top-level menu item.
	 */
	public function add_menu_page(): void {
		$hook = add_menu_page(
			__( 'Bestenberg', 'bestenberg' ),
			__( 'Bestenberg', 'bestenberg' ),
			self::CAPABILITY,
			self::SLUG,
			array( $this, 'render' ),
			'dashicons-layout',
			59
		);

		$this->hook_suffix = $hook;
	}

	/**
	 * Prints the mount point for the React app.
	 */
	public function render(): void {
		if ( ! is_readable( self::asset_file() ) ) {
			wp_admin_notice(
				esc_html__( 'Bestenberg editor assets are missing. Run `pnpm build`.', 'bestenberg' ),
				array( 'type' => 'error' )
			);
			return;
		}

		printf(
			'<div id="%1$s" class="bestenberg-root" aria-busy="true">%2$s</div>',
			esc_attr( self::ROOT_ID ),
			esc_html__( 'Loading Bestenberg…', 'bestenberg' )
		);
	}

	/**
	 * Enqueues the editor bundle on our page only.
	 *
	 * @param string $hook_suffix Current admin page hook suffix.
	 */
	public function enqueue_assets( string $hook_suffix ): void {
		if ( '' === $this->hook_suffix || $hook_suffix !== $this->hook_suffix ) {
			return;
		}

		$asset_file = self::asset_file();
		if ( ! is_readable( $asset_file ) ) {
			return;
		}

		/**
		 * Asset metadata generated by @wordpress/scripts.
		 *
		 * @var array{dependencies: string[], version: string} $asset
		 */
		$asset = require $asset_file;

		wp_enqueue_script(
			self::HANDLE,
			BESTENBERG_URL . 'build/editor/index.js',
			$asset['dependencies'],
			$asset['version'],
			array( 'in_footer' => true )
		);

		if ( is_readable( BESTENBERG_DIR . 'build/editor/index.css' ) ) {
			wp_enqueue_style(
				self::HANDLE,
				BESTENBERG_URL . 'build/editor/index.css',
				array(),
				$asset['version']
			);
		}
	}

	/**
	 * Path to the asset metadata generated by @wordpress/scripts.
	 */
	private static function asset_file(): string {
		return BESTENBERG_DIR . 'build/editor/index.asset.php';
	}

	/**
	 * Adds a body class used by the full-screen styles.
	 *
	 * @param string $classes Space-separated admin body classes.
	 */
	public function body_class( string $classes ): string {
		$screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;
		if ( null !== $screen && '' !== $this->hook_suffix && $screen->id === $this->hook_suffix ) {
			$classes .= ' bestenberg-fullscreen';
		}
		return $classes;
	}
}
